### PR TITLE
Migrate to AndroidX

### LINKED ISSUE #112: Migrate library to AndroidX
This Pusher library still relies on 2 years old Android Support libraries.

Google is encouraging all developers to migrate from using Support Libraries to AndroidX as the former is not receiving any more updates.

More info at: https://developer.android.com/jetpack/androidx/migrate

This is the last external dependency of our project to use the older support libraries and it's currently preventing us from disabling Jetifier.

Please consider upgrading to AndroidX.

### PR DESCRIPTION
**Pull request by julioromano**
This commit was auto generated by Android Studio's "Refactor -> Migrate to AndroidX..." feature.

More info at: https://developer.android.com/jetpack/androidx/migrate

Closes #112

### CODE REVIEW

**Comment by julioromano** [comment]
There's a test failing but it was failing on 'master' too. Not sure why.

**Comment by julioromano** [comment]
@daniellevass 👋 I wanted to add you as a reviewer on this PR but I somehow can't.

**Comment by julioromano** [comment]
@luismfonseca  Can you please assign a reviewer to this?

**Review by devdreamsolution — APPROVED** [review]

**Comment by luismfonseca** [comment]
@julioromano sorry for the late response, I no longer work at Pusher but @jonathanlloyd or @TomKemp might be able to assist you with this.

**Comment by julioromano** [comment]
@jonathanlloyd @TomKemp can anyone assist on this? Please see the related issue https://github.com/pusher/push-notifications-android/issues/112 for reference

**Pull request closed without merging**
